dist: trusty
sudo: true
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS = $keyfile
  - PROJECT_NAME_STG = "studious-set-280411"
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- yes | ssh -i ./deploy_key anhelina@34.75.250.168 pwd
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- echo $keyfile | base64 --decode -i > ${HOME}/studious-set-280411-db6dcfed0d74.json
jobs:
  include:
  - stage: build docker image
    script:
    - chmod +x test.sh;
    - "./test.sh;"
  - stage: lint
    if: branch = master OR branch = dev
    script: npm run lint
  - stage: build
    if: branch = master OR branch = dev
    script: npm run build
