dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules
    - "$HOME/google-cloud-sdk/"

services:
    - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS = $keyfile
 #   - PROJECT_NAME_STG=<YOUR_PROJECT_NAME>

 before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; 
    then rm -rf $HOME/google-cloud-sdk; 
    export CLOUDSDK_CORE_DISABLE_PROMPTS=1; 
    curl https://sdk.cloud.google.com | bash;
     fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update

jobs:
    include:
       - stage: build docker image
      
         script:
          - 'if [ "${TRAVIS_PULL_REQUEST}" = "true" ];
          then chmod +x test.sh;
                     ./ test.sh;
          fi'

       - stage: lint
         if: branch = master OR branch = dev
         script: npm run lint


       - stage: build  
         if: branch = master OR branch = dev
         script: npm run build

