dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules
    - "$HOME/google-cloud-sdk/"

services:
    - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS = $keyfile
    - PROJECT_NAME_STG = "studious-set-280411"

before_install:
  - - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
      CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null;
      fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update

jobs:
    include:
       - stage: build docker image
         if: branch = master OR branch = dev
         script:
          - docker build -t gcr.io/studious-set-280411/travis-ci-build-stages-demo .
          - echo $keyfile | base64 --decode -i > ${HOME}/studious-set-280411-db6dcfed0d74.json
          - gcloud auth activate-service-account --key-file ${HOME}/studious-set-280411-db6dcfed0d74.json
          - gcloud --quiet config set project studious-set-280411
          - gcloud docker push gcr.io/studious-set-280411/travis-ci-build-stages-demo     
      
       - stage: lint
         if: branch = master OR branch = dev
         script: npm run lint


       - stage: build  
         if: branch = master OR branch = dev
         script: npm run build

