dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules
    - "$HOME/google-cloud-sdk/"

services:
    - docker

jobs:
    include:
       - stage: build docker image
      
         script:
          - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
          then chmod +x test.sh;
                     ./ test.sh;
          fi'
          - 'if [ "${TRAVIS_PULL_REQUEST}" = "true" ]; 
              then echo "  ";
              fi   '
       - stage: lint
         if: branch = master OR branch = dev
         script: npm run lint


       - stage: build  
         if: branch = master OR branch = dev
         script: npm run build

