dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

services:
    - docker

jobs:
    include:
       - stage: build docker image
         if: $TRAVIS_PULL_REQUEST = true
         script:
            - docker build -t travis-ci-build-stages-demo .
            - docker images
            - docker tag travis-ci-build-stages-demo travis-ci-build-stages-demo       
            - docker run -d --rm travis-ci-build-stages-demo

       - stage: lint
         if: branch = master OR branch = dev
         script: npm run lint


       - stage: build  
         if: branch = master OR branch = dev
         script: npm run build
