dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

services:
    - docker

jobs:
    include:
       - stage: build docker image
         script:
          - 'if [ "${TRAVIS_PULL_REQUEST}" = "true" ];
          then surge ./ test.sh
            fi'
       - stage: lint
         if: branch = master OR branch = dev
         script: npm run lint


       - stage: build  
         if: branch = master OR branch = dev
         script: npm run build
