dist: trusty
sudo: true
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS = $keyfile
  - PROJECT_NAME_STG = "studious-set-280411"
before_install:
- pyenv global 3.5 
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600  id_rsa
- ssh-add  id_rsa
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- echo $keyfile | base64 --decode -i > ${HOME}/studious-set-280411-db6dcfed0d74.json
jobs:
  include:
    
  - stage: build docker image
    script:
    - chmod +x test.sh;
    - "./test.sh;"
  - stage: lint
    if: branch = master OR branch = dev
    script: npm run lint
  - stage: build
    if: branch = master OR branch = dev
    script: npm run build
