apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: angular-stage-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600