apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: angular-stage-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: angular-stage-service
          servicePort: 80